---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: beblue
# description will be included in the image's metadata
description: bebebeba.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-silverblue
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-lto/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-lto-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/trixieua/mesa-clang/repo/fedora-%OS_VERSION%/trixieua-mesa-clang-fedora-%OS_VERSION%.repo?arch=x86_64
      - https://copr.fedorainfracloud.org/coprs/trixieua/morewaita-icon-theme/repo/fedora-%OS_VERSION%/trixieua-morewaita-icon-theme-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/zeno/scrcpy/repo/fedora-%OS_VERSION%/zeno-scrcpy-fedora-%OS_VERSION%.repo

    keys:
      - https://packages.microsoft.com/keys/microsoft.asc

    install:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm


  - type: rpm-ostree

    install:
      - adw-gtk3-theme
      - code
      - distrobox
      - fastfetch
      - gparted
      - htop
      - irqbalance
      - kernel-cachyos-lto
      - kernel-cachyos-lto-devel-matched
      - morewaita-icon-theme
      - scrcpy
      - sysfsutils
      - wireguard-tools
      

    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - gnome-classic-session
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-core
      - kernel-modules-extra

  - type: rpm-ostree
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
        packages:
          - mutter
          - mutter-common
          - gdm
          - gnome-shell
          - gnome-shell-common
          - xorg-x11-server-Xwayland

  - type: rpm-ostree
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/trixieua/mesa-clang/repo/fedora-%OS_VERSION%/trixieua-mesa-clang-fedora-%OS_VERSION%.repo?arch=x86_64
        packages:
          - mesa-filesystem
          - mesa-libgbm
          - mesa-dri-drivers
          - mesa-libEGL
          - mesa-libGL
          - mesa-vulkan-drivers
          - mesa-va-drivers

  - type: systemd
    system:
      enabled:
        - irqbalance.service

  - type: gnome-extensions
    install:
      - 517 # Caffeine
      - 3733 # Tiling Assistant
      - 6807 # System Monitor

  - type: initramfs
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
